name: ci

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script_stop: true
        script: |
          docker stop cdg_bot_container || true && docker rm cdg_bot_container || true
          docker build --ssh default=./.ssh/id_rsa -t chapardev/cdg_bot git@github.com:ChaPerx64/CDG_Bot.git
          docker run --name cdg_bot_container --env-file './bots/cdg_bot/.env.prod' --pull always --rm -d chapardev/cdg_bot
